// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/processor_message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_proto_processor_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_processor_message_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMessageRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageResponse) Reset() {
	*x = CreateMessageResponse{}
	mi := &file_proto_processor_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageResponse) ProtoMessage() {}

func (x *CreateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_processor_message_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMessageResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetMessageByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageByIDRequest) Reset() {
	*x = GetMessageByIDRequest{}
	mi := &file_proto_processor_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageByIDRequest) ProtoMessage() {}

func (x *GetMessageByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageByIDRequest.ProtoReflect.Descriptor instead.
func (*GetMessageByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_processor_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessageByIDRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetMessageByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageByIDResponse) Reset() {
	*x = GetMessageByIDResponse{}
	mi := &file_proto_processor_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageByIDResponse) ProtoMessage() {}

func (x *GetMessageByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageByIDResponse.ProtoReflect.Descriptor instead.
func (*GetMessageByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_processor_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessageByIDResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetMessageByOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint32                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageByOffsetRequest) Reset() {
	*x = GetMessageByOffsetRequest{}
	mi := &file_proto_processor_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageByOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageByOffsetRequest) ProtoMessage() {}

func (x *GetMessageByOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageByOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetMessageByOffsetRequest) Descriptor() ([]byte, []int) {
	return file_proto_processor_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessageByOffsetRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetMessageByOffsetRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessageByOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageByOffsetResponse) Reset() {
	*x = GetMessageByOffsetResponse{}
	mi := &file_proto_processor_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageByOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageByOffsetResponse) ProtoMessage() {}

func (x *GetMessageByOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageByOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetMessageByOffsetResponse) Descriptor() ([]byte, []int) {
	return file_proto_processor_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessageByOffsetResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_proto_processor_message_proto protoreflect.FileDescriptor

const file_proto_processor_message_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/processor_message.proto\x12\amessage\"Y\n" +
	"\x14CreateMessageRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"'\n" +
	"\x15CreateMessageResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"'\n" +
	"\x15GetMessageByIDRequest\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\tR\x02ID\"4\n" +
	"\x16GetMessageByIDResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages\"I\n" +
	"\x19GetMessageByOffsetRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"8\n" +
	"\x1aGetMessageByOffsetResponse\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages2\x8a\x02\n" +
	"\n" +
	"msgService\x12N\n" +
	"\rCreateMessage\x12\x1d.message.CreateMessageRequest\x1a\x1e.message.CreateMessageResponse\x12M\n" +
	"\n" +
	"GetMessage\x12\x1e.message.GetMessageByIDRequest\x1a\x1f.message.GetMessageByIDResponse\x12]\n" +
	"\x12GetMessageByOffset\x12\".message.GetMessageByOffsetRequest\x1a#.message.GetMessageByOffsetResponseB\fZ\n" +
	"messagepb/b\x06proto3"

var (
	file_proto_processor_message_proto_rawDescOnce sync.Once
	file_proto_processor_message_proto_rawDescData []byte
)

func file_proto_processor_message_proto_rawDescGZIP() []byte {
	file_proto_processor_message_proto_rawDescOnce.Do(func() {
		file_proto_processor_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_processor_message_proto_rawDesc), len(file_proto_processor_message_proto_rawDesc)))
	})
	return file_proto_processor_message_proto_rawDescData
}

var file_proto_processor_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_processor_message_proto_goTypes = []any{
	(*CreateMessageRequest)(nil),       // 0: message.CreateMessageRequest
	(*CreateMessageResponse)(nil),      // 1: message.CreateMessageResponse
	(*GetMessageByIDRequest)(nil),      // 2: message.GetMessageByIDRequest
	(*GetMessageByIDResponse)(nil),     // 3: message.GetMessageByIDResponse
	(*GetMessageByOffsetRequest)(nil),  // 4: message.GetMessageByOffsetRequest
	(*GetMessageByOffsetResponse)(nil), // 5: message.GetMessageByOffsetResponse
}
var file_proto_processor_message_proto_depIdxs = []int32{
	0, // 0: message.msgService.CreateMessage:input_type -> message.CreateMessageRequest
	2, // 1: message.msgService.GetMessage:input_type -> message.GetMessageByIDRequest
	4, // 2: message.msgService.GetMessageByOffset:input_type -> message.GetMessageByOffsetRequest
	1, // 3: message.msgService.CreateMessage:output_type -> message.CreateMessageResponse
	3, // 4: message.msgService.GetMessage:output_type -> message.GetMessageByIDResponse
	5, // 5: message.msgService.GetMessageByOffset:output_type -> message.GetMessageByOffsetResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_processor_message_proto_init() }
func file_proto_processor_message_proto_init() {
	if File_proto_processor_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_processor_message_proto_rawDesc), len(file_proto_processor_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_processor_message_proto_goTypes,
		DependencyIndexes: file_proto_processor_message_proto_depIdxs,
		MessageInfos:      file_proto_processor_message_proto_msgTypes,
	}.Build()
	File_proto_processor_message_proto = out.File
	file_proto_processor_message_proto_goTypes = nil
	file_proto_processor_message_proto_depIdxs = nil
}
